/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.hasco.MSFS.ui;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import tw.com.hasco.MSFS.FS.FSBasic;
import tw.com.hasco.MSFS.Observer;

/**
 *
 * @author DELL
 */
public class DataFrame extends javax.swing.JFrame implements Observer{
    int currTime;
    // List<Double> times;
    /**
     * Creates new form DataFrame
     */
    public DataFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/draw/h.jpg")));
        this.setTitle("Data 資料圖");
        currTime = -1;
        // times = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pitchPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        yawPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        altPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        aoaPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        betaPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        rollPanel = new tw.com.hasco.MSFS.ui.DataPanel();
        pitchLabel = new javax.swing.JLabel();
        rollLabel = new javax.swing.JLabel();
        yawLabel = new javax.swing.JLabel();
        altLabel = new javax.swing.JLabel();
        aoaLabel = new javax.swing.JLabel();
        betaLabel = new javax.swing.JLabel();
        upTimePanel = new tw.com.hasco.MSFS.ui.UpTimePanel();
        downTimePanel = new tw.com.hasco.MSFS.ui.DownTimePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pitchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pitchPanelLayout = new javax.swing.GroupLayout(pitchPanel);
        pitchPanel.setLayout(pitchPanelLayout);
        pitchPanelLayout.setHorizontalGroup(
            pitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pitchPanelLayout.setVerticalGroup(
            pitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        yawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout yawPanelLayout = new javax.swing.GroupLayout(yawPanel);
        yawPanel.setLayout(yawPanelLayout);
        yawPanelLayout.setHorizontalGroup(
            yawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        yawPanelLayout.setVerticalGroup(
            yawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        altPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout altPanelLayout = new javax.swing.GroupLayout(altPanel);
        altPanel.setLayout(altPanelLayout);
        altPanelLayout.setHorizontalGroup(
            altPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        altPanelLayout.setVerticalGroup(
            altPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        aoaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout aoaPanelLayout = new javax.swing.GroupLayout(aoaPanel);
        aoaPanel.setLayout(aoaPanelLayout);
        aoaPanelLayout.setHorizontalGroup(
            aoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        aoaPanelLayout.setVerticalGroup(
            aoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        betaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout betaPanelLayout = new javax.swing.GroupLayout(betaPanel);
        betaPanel.setLayout(betaPanelLayout);
        betaPanelLayout.setHorizontalGroup(
            betaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        betaPanelLayout.setVerticalGroup(
            betaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        rollPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout rollPanelLayout = new javax.swing.GroupLayout(rollPanel);
        rollPanel.setLayout(rollPanelLayout);
        rollPanelLayout.setHorizontalGroup(
            rollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rollPanelLayout.setVerticalGroup(
            rollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pitchLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        pitchLabel.setText("Pitch");

        rollLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        rollLabel.setText("Roll");

        yawLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        yawLabel.setText("Yaw");

        altLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        altLabel.setText("Alt");

        aoaLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        aoaLabel.setText("Aoa");

        betaLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        betaLabel.setText("Beta");

        javax.swing.GroupLayout upTimePanelLayout = new javax.swing.GroupLayout(upTimePanel);
        upTimePanel.setLayout(upTimePanelLayout);
        upTimePanelLayout.setHorizontalGroup(
            upTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        upTimePanelLayout.setVerticalGroup(
            upTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout downTimePanelLayout = new javax.swing.GroupLayout(downTimePanel);
        downTimePanel.setLayout(downTimePanelLayout);
        downTimePanelLayout.setHorizontalGroup(
            downTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        downTimePanelLayout.setVerticalGroup(
            downTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pitchLabel)
                    .addComponent(rollLabel)
                    .addComponent(yawLabel)
                    .addComponent(altLabel)
                    .addComponent(aoaLabel)
                    .addComponent(betaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aoaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(betaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pitchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(upTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pitchLabel)
                    .addComponent(pitchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yawLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aoaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aoaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(betaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(betaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataFrame().setVisible(true);
            }
        });
    }
public void clearData() {
    upTimePanel.clearData();
    downTimePanel.clearData();
    pitchPanel.clearData();
    rollPanel.clearData();
    yawPanel.clearData();
    altPanel.clearData();
    aoaPanel.clearData();
    betaPanel.clearData();     
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altLabel;
    private tw.com.hasco.MSFS.ui.DataPanel altPanel;
    private javax.swing.JLabel aoaLabel;
    private tw.com.hasco.MSFS.ui.DataPanel aoaPanel;
    private javax.swing.JLabel betaLabel;
    private tw.com.hasco.MSFS.ui.DataPanel betaPanel;
    private tw.com.hasco.MSFS.ui.DownTimePanel downTimePanel;
    private javax.swing.JLabel pitchLabel;
    private tw.com.hasco.MSFS.ui.DataPanel pitchPanel;
    private javax.swing.JLabel rollLabel;
    private tw.com.hasco.MSFS.ui.DataPanel rollPanel;
    private tw.com.hasco.MSFS.ui.UpTimePanel upTimePanel;
    private javax.swing.JLabel yawLabel;
    private tw.com.hasco.MSFS.ui.DataPanel yawPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(FSBasic fsBasic) {
        int time = fsBasic.hour()*3600 + fsBasic.min() *60 + fsBasic.sec();
        if (currTime == time) {
            return;
        }
        currTime = time;
        upTimePanel.addData(currTime);
        downTimePanel.addData(currTime);
        pitchPanel.addData(fsBasic.pitch());
        rollPanel.addData(fsBasic.bank());
        yawPanel.addData(fsBasic.heading());
        altPanel.addData(fsBasic.altitude());
        aoaPanel.addData(fsBasic.aoa());
        betaPanel.addData(fsBasic.beta());
    }
}
