/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.hasco.MSFS.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author DELL
 */
public class DimPanel extends javax.swing.JPanel {

    double max, min;
    double origMax, origMin;
    int w, h;

    /**
     * Creates new form DimPanel
     */
    public DimPanel() {
        initComponents();
        setMaxMin(5, -5);
    }

    public void setMaxMin(double max, double min) {
        this.max = origMax = max;
        this.min = origMin = min;
    }

    public void addData(Double d) {
        max = (max >= d) ? max : d;
        min = (min <= d) ? min : d;
        repaint();
    }

    public void clearData() {
        max = origMax;
        min = origMin;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
@Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        w = this.getWidth() - 1;
        h = this.getHeight() - 1;
        for (int i = 0; i < 5; ++i) {
            int y = i * h / 4;
            int x0 = 3*w  / 4, x1 = w;
            double val = max - (max - min) * i / 4;
            g2d.drawLine(x0, y, x1, y);
            g2d.drawString(String.format("%.1f", val), w / 2 , y);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
