/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.hasco.MSFS.ui;

import javax.swing.JFrame;
import javax.swing.JPanel;
import tw.com.hasco.MSFS.FS.FSBasic;
import tw.com.hasco.MSFS.locale.LocaleManager;

/**
 *
 * @author ktc
 */
public class LlaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlanePanel
     */
    public LlaPanel() {
        initComponents();
        setLabelsTest();

    }

    private void setLabelsTest() {
        this.typeLabel.setText(LocaleManager.getInstance().getString("type"));
        this.timeLabel.setText(LocaleManager.getInstance().getString("time"));
        this.latitudeLabel.setText(LocaleManager.getInstance().getString("latitude"));
        this.longitudeLabel.setText(LocaleManager.getInstance().getString("longitude"));
        this.altitudeLabel.setText(LocaleManager.getInstance().getString("altitude"));
        this.flyAltitudeLabel.setText(LocaleManager.getInstance().getString("flyAltitude"));
        this.groundAltitudeLabel.setText(LocaleManager.getInstance().getString("groundAltitude"));
        this.headingLabel.setText(LocaleManager.getInstance().getString("heading"));
        this.pitchLabel.setText(LocaleManager.getInstance().getString("pitch"));
        this.bankLabel.setText(LocaleManager.getInstance().getString("bank"));
        this.magneticHeadingLabel.setText(LocaleManager.getInstance().getString("magneticHeading"));
        this.aoaLabel.setText(LocaleManager.getInstance().getString("aoa"));
        this.betaLabel.setText(LocaleManager.getInstance().getString("beta"));
        this.indicatedAirSpeedLabel.setText(LocaleManager.getInstance().getString("indicatedAirSpeed"));
        this.trueAirSpeedLabel.setText(LocaleManager.getInstance().getString("trueAirSpeed"));
        this.machSpeedLabel.setText(LocaleManager.getInstance().getString("machSpeed"));
        this.verticalSpeedLabel.setText(LocaleManager.getInstance().getString("verticalSpeed"));
        this.gForceLabel.setText(LocaleManager.getInstance().getString("gForce"));
        this.groundSpeedLabel.setText(LocaleManager.getInstance().getString("groundSpeed"));
        this.windDirectionLabel.setText(LocaleManager.getInstance().getString("windDirection"));
        this.windSpeedLabel.setText(LocaleManager.getInstance().getString("windSpeed"));
        this.navigateFrequencyLabel.setText(LocaleManager.getInstance().getString("navigateFrequency"));
        this.navigateIDLabel.setText(LocaleManager.getInstance().getString("navigateID"));
        this.navigateNameLabel.setText(LocaleManager.getInstance().getString("navigateName"));
        this.localizerDevLabel.setText(LocaleManager.getInstance().getString("localizerDev"));
        this.glideslopeDevLabel.setText(LocaleManager.getInstance().getString("glideslopeDev"));
        this.dmeLabel.setText(LocaleManager.getInstance().getString("dme"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        latitudeLabel = new javax.swing.JLabel();
        altitudeLabel = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        latitudeTextField = new javax.swing.JTextField();
        altitudeTextField = new javax.swing.JTextField();
        flyAltitudeLabel = new javax.swing.JLabel();
        longitudeLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        longitudeTextField = new javax.swing.JTextField();
        groundAltitudeTextField = new javax.swing.JTextField();
        groundAltitudeLabel = new javax.swing.JLabel();
        flyAltitudeTextField = new javax.swing.JTextField();
        verticalSpeedLabel = new javax.swing.JLabel();
        verticalSpeedTextField = new javax.swing.JTextField();
        indicatedAirSpeedLabel = new javax.swing.JLabel();
        indicatedAirSpeedTextField = new javax.swing.JTextField();
        windDirectionLabel = new javax.swing.JLabel();
        windDirectionTextField = new javax.swing.JTextField();
        trueAirSpeedLabel = new javax.swing.JLabel();
        trueAirSpeedTextField = new javax.swing.JTextField();
        windSpeedLabel = new javax.swing.JLabel();
        windSpeedTextField = new javax.swing.JTextField();
        groundSpeedLabel = new javax.swing.JLabel();
        groundSpeedTextField = new javax.swing.JTextField();
        machSpeedLabel = new javax.swing.JLabel();
        machSpeedTextField = new javax.swing.JTextField();
        gForceLabel = new javax.swing.JLabel();
        gForceTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        headingTextField = new javax.swing.JTextField();
        pitchLabel = new javax.swing.JLabel();
        pitchTextField = new javax.swing.JTextField();
        bankTextField = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        betaTextField = new javax.swing.JTextField();
        betaLabel = new javax.swing.JLabel();
        aoaTextField = new javax.swing.JTextField();
        aoaLabel = new javax.swing.JLabel();
        magneticHeadingTextField = new javax.swing.JTextField();
        magneticHeadingLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        localizerDevTextField = new javax.swing.JTextField();
        glideslopeDevLabel = new javax.swing.JLabel();
        glideslopeDevTextField = new javax.swing.JTextField();
        navigateNameLabel = new javax.swing.JLabel();
        navigateNameTextField = new javax.swing.JTextField();
        dmeLabel = new javax.swing.JLabel();
        dmeTextField = new javax.swing.JTextField();
        navigateFrequencyLabel = new javax.swing.JLabel();
        localizerDevLabel = new javax.swing.JLabel();
        navigateFrequencyTextField = new javax.swing.JTextField();
        navigateIDLabel = new javax.swing.JLabel();
        navigateIDTextField = new javax.swing.JTextField();

        typeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        typeLabel.setText("機型");

        latitudeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        latitudeLabel.setText("緯度");

        altitudeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        altitudeLabel.setText("高度");

        typeTextField.setEditable(false);
        typeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        typeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        latitudeTextField.setEditable(false);
        latitudeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        latitudeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        altitudeTextField.setEditable(false);
        altitudeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        altitudeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        flyAltitudeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        flyAltitudeLabel.setText("離地");

        longitudeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        longitudeLabel.setText("經度");

        timeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        timeLabel.setText("時間");

        timeTextField.setEditable(false);
        timeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        timeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        longitudeTextField.setEditable(false);
        longitudeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        longitudeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        groundAltitudeTextField.setEditable(false);
        groundAltitudeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        groundAltitudeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        groundAltitudeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        groundAltitudeLabel.setText("地高");

        flyAltitudeTextField.setEditable(false);
        flyAltitudeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        flyAltitudeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        verticalSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        verticalSpeedLabel.setText("垂直速率 VS");

        verticalSpeedTextField.setEditable(false);
        verticalSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        verticalSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        verticalSpeedTextField.setToolTipText("");

        indicatedAirSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        indicatedAirSpeedLabel.setText("儀表空速 IAS");

        indicatedAirSpeedTextField.setEditable(false);
        indicatedAirSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        indicatedAirSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        indicatedAirSpeedTextField.setToolTipText("");

        windDirectionLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        windDirectionLabel.setText("風向");

        windDirectionTextField.setEditable(false);
        windDirectionTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        windDirectionTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        windDirectionTextField.setToolTipText("");

        trueAirSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        trueAirSpeedLabel.setText("真實空速 TAS");

        trueAirSpeedTextField.setEditable(false);
        trueAirSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        trueAirSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        trueAirSpeedTextField.setToolTipText("");

        windSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        windSpeedLabel.setText("風速");

        windSpeedTextField.setEditable(false);
        windSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        windSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        windSpeedTextField.setToolTipText("");

        groundSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        groundSpeedLabel.setText("對地速度 GS");

        groundSpeedTextField.setEditable(false);
        groundSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        groundSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        groundSpeedTextField.setToolTipText("");

        machSpeedLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        machSpeedLabel.setText("馬赫");

        machSpeedTextField.setEditable(false);
        machSpeedTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        machSpeedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        machSpeedTextField.setToolTipText("");

        gForceLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        gForceLabel.setText("G 值");

        gForceTextField.setEditable(false);
        gForceTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        gForceTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gForceTextField.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(groundSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groundSpeedTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(trueAirSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trueAirSpeedTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(indicatedAirSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indicatedAirSpeedTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(verticalSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verticalSpeedTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(longitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longitudeTextField)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(machSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(machSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gForceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gForceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(windSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(windSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(windDirectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(windDirectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(groundAltitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groundAltitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(flyAltitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flyAltitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(latitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(latitudeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(altitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latitudeLabel)
                    .addComponent(latitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altitudeLabel)
                    .addComponent(altitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longitudeLabel)
                    .addComponent(longitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groundAltitudeLabel)
                    .addComponent(groundAltitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verticalSpeedLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(verticalSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flyAltitudeLabel)
                        .addComponent(flyAltitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indicatedAirSpeedLabel)
                    .addComponent(indicatedAirSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windDirectionLabel)
                    .addComponent(windDirectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trueAirSpeedLabel)
                    .addComponent(trueAirSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windSpeedLabel)
                    .addComponent(windSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groundSpeedLabel)
                    .addComponent(groundSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(machSpeedLabel)
                    .addComponent(machSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gForceLabel)
                    .addComponent(gForceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(512, 100));

        headingLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        headingLabel.setText("方位角 H");

        headingTextField.setEditable(false);
        headingTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        headingTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        headingTextField.setToolTipText("");

        pitchLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        pitchLabel.setText("俯仰角 P");

        pitchTextField.setEditable(false);
        pitchTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        pitchTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pitchTextField.setToolTipText("");

        bankTextField.setEditable(false);
        bankTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bankTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bankTextField.setToolTipText("");

        bankLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bankLabel.setText("滾轉角 R");

        betaTextField.setEditable(false);
        betaTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        betaTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        betaTextField.setToolTipText("");

        betaLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        betaLabel.setText("側滑角 B");

        aoaTextField.setEditable(false);
        aoaTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        aoaTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aoaTextField.setToolTipText("");

        aoaLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        aoaLabel.setText("攻角 AOA");

        magneticHeadingTextField.setEditable(false);
        magneticHeadingTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        magneticHeadingTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        magneticHeadingTextField.setToolTipText("");

        magneticHeadingLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        magneticHeadingLabel.setText("磁方角 M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pitchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pitchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headingTextField)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(magneticHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magneticHeadingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aoaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(magneticHeadingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(headingLabel)
                        .addComponent(headingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aoaLabel)
                        .addComponent(aoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(magneticHeadingLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pitchLabel)
                        .addComponent(pitchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bankLabel)
                            .addComponent(bankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betaLabel)
                            .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        localizerDevTextField.setEditable(false);
        localizerDevTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        localizerDevTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        localizerDevTextField.setToolTipText("");

        glideslopeDevLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        glideslopeDevLabel.setText("Glideslope 偏差");

        glideslopeDevTextField.setEditable(false);
        glideslopeDevTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        glideslopeDevTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        glideslopeDevTextField.setToolTipText("");

        navigateNameLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateNameLabel.setText("名稱");

        navigateNameTextField.setEditable(false);
        navigateNameTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateNameTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        navigateNameTextField.setToolTipText("");

        dmeLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        dmeLabel.setText("DME");

        dmeTextField.setEditable(false);
        dmeTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        dmeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dmeTextField.setToolTipText("");

        navigateFrequencyLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateFrequencyLabel.setText("導航 NAV1 頻率");

        localizerDevLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        localizerDevLabel.setText("Localizer 偏差");

        navigateFrequencyTextField.setEditable(false);
        navigateFrequencyTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateFrequencyTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        navigateFrequencyTextField.setToolTipText("");

        navigateIDLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateIDLabel.setText("代號");

        navigateIDTextField.setEditable(false);
        navigateIDTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        navigateIDTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        navigateIDTextField.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(localizerDevLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navigateFrequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigateFrequencyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(localizerDevTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(navigateIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navigateIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navigateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navigateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(glideslopeDevLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glideslopeDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dmeTextField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navigateFrequencyLabel)
                    .addComponent(navigateFrequencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigateIDLabel)
                    .addComponent(navigateIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigateNameLabel)
                    .addComponent(navigateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localizerDevLabel)
                    .addComponent(localizerDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glideslopeDevLabel)
                    .addComponent(glideslopeDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dmeLabel)
                    .addComponent(dmeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altitudeLabel;
    private javax.swing.JTextField altitudeTextField;
    private javax.swing.JLabel aoaLabel;
    private javax.swing.JTextField aoaTextField;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JTextField bankTextField;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JTextField betaTextField;
    private javax.swing.JLabel dmeLabel;
    private javax.swing.JTextField dmeTextField;
    private javax.swing.JLabel flyAltitudeLabel;
    private javax.swing.JTextField flyAltitudeTextField;
    private javax.swing.JLabel gForceLabel;
    private javax.swing.JTextField gForceTextField;
    private javax.swing.JLabel glideslopeDevLabel;
    private javax.swing.JTextField glideslopeDevTextField;
    private javax.swing.JLabel groundAltitudeLabel;
    private javax.swing.JTextField groundAltitudeTextField;
    private javax.swing.JLabel groundSpeedLabel;
    private javax.swing.JTextField groundSpeedTextField;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JTextField headingTextField;
    private javax.swing.JLabel indicatedAirSpeedLabel;
    private javax.swing.JTextField indicatedAirSpeedTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel latitudeLabel;
    private javax.swing.JTextField latitudeTextField;
    private javax.swing.JLabel localizerDevLabel;
    private javax.swing.JTextField localizerDevTextField;
    private javax.swing.JLabel longitudeLabel;
    private javax.swing.JTextField longitudeTextField;
    private javax.swing.JLabel machSpeedLabel;
    private javax.swing.JTextField machSpeedTextField;
    private javax.swing.JLabel magneticHeadingLabel;
    private javax.swing.JTextField magneticHeadingTextField;
    private javax.swing.JLabel navigateFrequencyLabel;
    private javax.swing.JTextField navigateFrequencyTextField;
    private javax.swing.JLabel navigateIDLabel;
    private javax.swing.JTextField navigateIDTextField;
    private javax.swing.JLabel navigateNameLabel;
    private javax.swing.JTextField navigateNameTextField;
    private javax.swing.JLabel pitchLabel;
    private javax.swing.JTextField pitchTextField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JLabel trueAirSpeedLabel;
    private javax.swing.JTextField trueAirSpeedTextField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JLabel verticalSpeedLabel;
    private javax.swing.JTextField verticalSpeedTextField;
    private javax.swing.JLabel windDirectionLabel;
    private javax.swing.JTextField windDirectionTextField;
    private javax.swing.JLabel windSpeedLabel;
    private javax.swing.JTextField windSpeedTextField;
    // End of variables declaration//GEN-END:variables
    
    public void update(FSBasic fsBasic) {
        // 更新飛機座標資料
        // 緯度
        latitudeTextField.setText(fsBasic.getLatitudeInDMS() + "  " + fsBasic.getLatitudeInDegree());
        // 經度
        this.longitudeTextField.setText(fsBasic.getLongitudeInDMS() + "  " + fsBasic.getLongitudeInDegree());
        // 飛行高度
        altitudeTextField.setText(fsBasic.getAltitudeInMeter());
        // 離地高度
        flyAltitudeTextField.setText(fsBasic.getFlyAltitude());
        // 地表標高
        groundAltitudeTextField.setText(fsBasic.getGroundAltitude());

        //更新飛機姿態資料
        // 方位角
        headingTextField.setText(fsBasic.getHeading());
        // 磁方角
        magneticHeadingTextField.setText(fsBasic.getMagneticHeading());
        // 俯仰角
        pitchTextField.setText(fsBasic.getPitch());
        // 滾轉角
        bankTextField.setText(fsBasic.getBank());
        // 攻角
        aoaTextField.setText(fsBasic.getAoa());
        // 測滑角
        betaTextField.setText(fsBasic.getBeta());

        //更新飛機速度資料
        // 儀表空速
        indicatedAirSpeedTextField.setText(fsBasic.getIndicatedAirSpeed());
        // 馬赫數
        machSpeedTextField.setText(fsBasic.getMachSpeed());
        // 真實空速
        trueAirSpeedTextField.setText(fsBasic.getTrueAirSpeed());
        // 對地速度
        groundSpeedTextField.setText(String.format("%s %s", fsBasic.getGroundSpeedInKnot(), fsBasic.getGroundSpeedInMeter()));
        //gsTextField.setText(null);
        // 垂直速率
        // verticalSpeedTextField.setText(fsBasic.getVerticalSpeedInFeet() + "  " + fsBasic.getVerticalSpeedInMeter());
        verticalSpeedTextField.setText(fsBasic.getVerticalSpeedInMeter());
        // 重力 G 值
        gForceTextField.setText(fsBasic.getGForce());
        // 風向
        windDirectionTextField.setText(fsBasic.getWindDirection());
        // 風速
        windSpeedTextField.setText(fsBasic.getWindSpeed());

        // 機型
        typeTextField.setText(fsBasic.getType());
        // 時間
        timeTextField.setText(fsBasic.getDisplayTime());

        //更新飛行員操控資料
        // NAV1
        // Frequency
        navigateFrequencyTextField.setText(fsBasic.getNavigateFrequency());
        // ID
        navigateIDTextField.setText(fsBasic.getNavigateID());
        // name
        navigateNameTextField.setText(fsBasic.getNavigateName());
        // NAV1-Localizer Needle
        localizerDevTextField.setText(fsBasic.getLocalizerDev());
        // NAV1-Glideslope Needle
        glideslopeDevTextField.setText(fsBasic.getGlideslopeDev());
        // DME Distance
        dmeTextField.setText(fsBasic.getDme());
    }

    public static void main(String[] args) throws InterruptedException {
        JFrame f = new JFrame("Demo");
        JPanel p = new LlaPanel();
        f.add(p);

        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setSize(600, 750);
        f.setVisible(true);
    }
}
