/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.hasco.MSFS.ui;

import java.awt.Toolkit;
import javax.swing.JFrame;
import tw.com.hasco.MSFS.FS.FSBasic;
import tw.com.hasco.MSFS.Observer;
import tw.com.hasco.MSFS.locale.LocaleManager;

/**
 *
 * @author DELL
 */
public class Plot6Frame extends javax.swing.JFrame implements Observer {

    int currTime;

    /**
     * Creates new form Data1Frame
     */
    public Plot6Frame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/draw/h.jpg")));
        this.setTitle(LocaleManager.getInstance("Taiwan").getString("fig_plot6"));
        setPanelInitVal();
    }

    private void setPanelInitVal() {
        this.pitchPanel.setVarLabel("Picth");
        this.pitchPanel.setMaxMin(5, -5);
        this.rollPanel.setVarLabel("Roll");
        this.rollPanel.setMaxMin(5, -5);
        this.yawPanel.setVarLabel("Yaw");
        this.yawPanel.setMaxMin(5, -5);
        this.altPanel.setVarLabel("Alt");
        this.altPanel.setMaxMin(10, 0);
        this.aoaPanel.setVarLabel("Aoa");
        this.aoaPanel.setMaxMin(5, -5);
        this.betaPanel.setVarLabel("Beta");
        this.betaPanel.setMaxMin(5, -5);
    }

    public void clearData() {
        upPanel.clearData();
        downPanel.clearData();
        pitchPanel.clearData();
        rollPanel.clearData();
        yawPanel.clearData();
        altPanel.clearData();
        aoaPanel.clearData();
        betaPanel.clearData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pitchPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        rollPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        yawPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        altPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        aoaPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        betaPanel = new tw.com.hasco.MSFS.ui.Plot1Panel();
        upPanel = new tw.com.hasco.MSFS.ui.UpPanel();
        downPanel = new tw.com.hasco.MSFS.ui.DownPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pitchPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        rollPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        yawPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        altPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        aoaPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        betaPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pitchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addComponent(rollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aoaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(betaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pitchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aoaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(betaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plot6Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plot6Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plot6Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plot6Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        LocaleManager l = LocaleManager.getInstance("China");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plot6Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tw.com.hasco.MSFS.ui.Plot1Panel altPanel;
    private tw.com.hasco.MSFS.ui.Plot1Panel aoaPanel;
    private tw.com.hasco.MSFS.ui.Plot1Panel betaPanel;
    private tw.com.hasco.MSFS.ui.DownPanel downPanel;
    private tw.com.hasco.MSFS.ui.Plot1Panel pitchPanel;
    private tw.com.hasco.MSFS.ui.Plot1Panel rollPanel;
    private tw.com.hasco.MSFS.ui.UpPanel upPanel;
    private tw.com.hasco.MSFS.ui.Plot1Panel yawPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(FSBasic fsBasic) {
        int time = fsBasic.hour() * 3600 + fsBasic.min() * 60 + fsBasic.sec();
        // if (currTime == time) {
        //     return;
        //}
        currTime = time;
        upPanel.addData(currTime);
        downPanel.addData(currTime);
        pitchPanel.addData(fsBasic.pitch());
        rollPanel.addData(fsBasic.bank());
        yawPanel.addData(fsBasic.heading());
        altPanel.addData(fsBasic.altitude());
        aoaPanel.addData(fsBasic.aoa());
        betaPanel.addData(fsBasic.beta());
    }
}
