/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.hasco.MSFS.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author DELL
 */
public class UpTimePanel extends javax.swing.JPanel {

    List<Integer> times;
    int w;
    int h;

    /**
     * Creates new form UpTiimePanel
     */
    public UpTimePanel() {
        initComponents();
        times = new ArrayList<>();
    }

    public void addData(int d) {
        times.add(d);
        repaint();
    }

    public void clearData() {
        times.clear();
    }

    private void drawAxis(Graphics2D g2d) {
        int x0 = 0;
        int y0 = h;
        int x1 = w;
        int y1 = h;
        g2d.drawLine(x0, y0, x1, y1);
        for(int i =0; i <= 10 ; ++i) {
            int x = i*w/10;
            g2d.drawLine(x, h-1, x, h/2);
        }
    }

    @Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        w = this.getWidth()-1;
        h = this.getHeight()-1;
        drawAxis(g2d);
        if (times.size() <= 1) {
            return;
        }

       
       int x0 = 0, y0 = h/2, x1 = w*9/10, y1= h/2;
       g2d.drawString(times.get(0).toString(), x0, y0);
        g2d.drawString(times.get(times.size() - 1).toString(), x1, y1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
